theme: jekyll-theme-minimal
title: [A blank website built just now]
description: [Don't be upset. I'm taking into much knowledge for better decoration
Remember the address, maybe next a few days you'll see a brand new one!]
title: [lpc66.vip]
