theme: jekyll-theme-minimal
description: [A blank website built just now.\n Don't be sad. I'm taking into much knowledge for better decoration. Remember the address, maybe next a few days you'll see a brand new one!]
title: [lpc66.vip]
