theme: jekyll-theme-minimal
description: [A blank website built just now. Don't be sad. I'm taking into knowledge for better decoration. Remember the address, maybe a few days later you'll see a brand new one!]
title: [lpc66.vip]
